spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-server:
            provider: oauth2
            client-name: Sign in with oauth2-server
            client-id: 111
            client-secret: 222
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1/login/oauth2/code/{registrationId}
            scope: openid, profile, phone, email
        provider:
          oauth2:
            authorization-uri: http://localhost:8888/oauth2/authorize
            token-uri: http://localhost:8888/oauth2/token
            jwk-set-uri: http://localhost:8888/oauth2/jwks
            user-info-uri: http://localhost:8888/userinfo
            issuer-uri: http://localhost:8888
            user-name-attribute: sub
            user-info-authentication-method: header
