spring:
  security:
    oauth2:
      server:
        host: 192.168.31.100:8888
      client:
        registration:
          oauth2-server:
            provider: oauth2
            client-name: Sign in with oauth2-server
            client-id: 111
            client-secret: 111
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.31.5/login/oauth2/code/{registrationId}
            scope: openid, profile, phone, email
        provider:
          oauth2:
            authorization-uri: http://${spring.security.oauth2.server.host}/oauth2/authorize
            token-uri: http://${spring.security.oauth2.server.host}/oauth2/token
            jwk-set-uri: http://${spring.security.oauth2.server.host}/oauth2/jwks
            user-info-uri: http://${spring.security.oauth2.server.host}/userinfo
            issuer-uri: http://${spring.security.oauth2.server.host}
            user-name-attribute: sub
            user-info-authentication-method: header
