server:
  port: 8888
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
spring:
  application:
    name: oauth2-server-service
secret-key:
  rsa:
    private-key-pem: /rsa/rsa_private_key_pkcs8.pem
    public-key-pem: /rsa/rsa_public_key_pkcs8.pem