server:
  port: 8888
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
spring:
  application:
    name: oauth2-server-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.100:3306/live-authorization-server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
live:
  oauth:
    rsa:
      private-key-pem: /rsa/rsa_private_key_pkcs8.pem
      public-key-pem: /rsa/rsa_public_key_pkcs8.pem
    login:
      server: ums/user
      username: /username
      phone: /phone